### ISSUE TITLE
Todo Methode Asthaufen Beurteilung

### ISSUE THREAD

**Issue by ratnanil** [wieselundco/erfolgskontrolle#7]
- [x] Bitte einzeilig einfügen: TABELLE (Zellen D1 bis M1 von WK_Qualitativ_Ah_20210408.xlsx)
- [x] Ist der Beschrieb der Methodik von Erhebung 3 verständlich?
- [x] wie heisst Adrians statistischen Verfahren (NAME?)?
- [x] Es macht wohl Sinn, ihn die Passage noch gegenlesen zu lassen(?).
- [x] (vgl. Foto x: 2021-03-31 11.30.21-1_snip.jpg grobes Astmaterial; Klasse 4. Foto y 2021-03-31 16.23.53_korr.jpg: feines Astmaterial; Klasse 1)

see #3
